# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0004_answer_not_an_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='hearts',
            field=models.PositiveIntegerField(default=0, verbose_name='Heart Count'),
        ),
        migrations.AddField(
            model_name='question',
            name='hearts',
            field=models.PositiveIntegerField(default=0, verbose_name='Heart Count'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
        migrations.AddField(
            model_name='heart',
            name='ans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qna.Answer'),
        ),
        migrations.AddField(
            model_name='heart',
            name='ques',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qna.Question'),
        ),
        migrations.AddField(
            model_name='heart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='heart',
            unique_together=set([('user', 'ans'), ('user', 'ques')]),
        ),
    ]
